"""Train a supervised model to predict which hint level (1, 2, 3)
will be most helpful for a student on a given question.

This uses the synthetic dataset generated by generate_hint_data.py.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

BASE_DIR = Path(__file__).parent
DATA_PATH = BASE_DIR / "datasets" / "hint_interactions.csv"
MODEL_PATH = BASE_DIR / "models" / "hint_model.joblib"


def load_data() -> tuple[pd.DataFrame, pd.Series]:
    df = pd.read_csv(DATA_PATH)

    feature_cols = [
        "correct_rate_topic",
        "avg_time_topic",
        "mastery",
        "hints_used_topic",
        "hints_used_question",
        "base_difficulty",
    ]
    X = df[feature_cols]
    y = df["label_hint_level"].astype(int)
    return X, y


def build_pipeline() -> Pipeline:
    numeric_features = [
        "correct_rate_topic",
        "avg_time_topic",
        "mastery",
        "hints_used_topic",
        "hints_used_question",
    ]
    categorical_features = ["base_difficulty"]

    numeric_transformer = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
        ]
    )

    categorical_transformer = Pipeline(
        steps=[
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numeric_features),
            ("cat", categorical_transformer, categorical_features),
        ]
    )

    clf = LogisticRegression(
        max_iter=1000,
        multi_class="multinomial",
    )

    return Pipeline(steps=[("preprocessor", preprocessor), ("clf", clf)])


def main() -> None:
    X, y = load_data()

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    pipe = build_pipeline()
    pipe.fit(X_train, y_train)

    y_pred = pipe.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"Test accuracy: {acc:.3f}")
    print(classification_report(y_test, y_pred))

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(pipe, MODEL_PATH)
    print(f"Saved model to {MODEL_PATH}")


if __name__ == "__main__":
    main()
